
server:
  port: 8080

property:
    test:
        name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
    list:
      - name: banana
        color: yellow
      - name: apple
        color: red
      - name: water melon
        color: green

datasource:
    url: jdbc:h2:mem:testdb

spring:
    h2:
        console:
            enabled: true

spring.test.database.replace: NONE
